### ISSUE TITLE
Details don't work as expected with lists

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#407]
I'd like to be able to use a hyperlinked list item as details header, and a sublist as the details body, as in the code shown below. However, the result is not as expected, in a number of ways:

(1) In the details header, the hyperlinked text doesn't render properly.
(2) Both inside and after the details block, the white space indicating list nestednesss is wrongly interpreted as code formatting.

Here's the intended code:

[details]...[/details] as an item inside a list, with a hyperlinked list item = the details header, with a collapsed sublist = the details.

```text
- [Charmcraft (`charmcraft`)](/t/5528) 
    - [details=[`charmcraft` commands](/t/6122)]
        - [analyze](/t/6116)
        - [clean](/t/6119)
        - [close](/t/6120)
        - [create-lib](/t/6121)
        - [fetch-lib](/t/6123)
        - [init](/t/6124)
        - [list-lib](/t/6125)
        - [login](/t/6126)
        - [logout](/t/6127)
        - [names](/t/6128)
        - [pack](/t/6129)
        - [publish-lib](/t/6131)
        - [register](/t/6133)
        - [register-bundle](/t/6132)
        - [release](/t/6134)
        - [resource-revisions](/t/6135)
        - [resources](/t/6136)
        - [revisions](/t/6137)
        - [status](/t/6138)
        - [upload-resource](/t/6139)
        - [upload](/t/6140)
        - [version](/t/6141)
        - [whoami](/t/6142)
[/details]	                                       
    - [Charmcraft deprecation notices](/t/4652)        
```

yields

![image](https://user-images.githubusercontent.com/38667005/170957742-7d6a7144-9254-4b8c-98fb-4f88214cc229.png)

Other issues are:
- A details block cannot be an item in a list.
- The header of a details block cannot be hyperlinked text.

All of these issues affect the result very much.

**Comment by jkfran** [comment]
Hi @tmihoc this is probably a Discourse limitation. I found this post from a user reporting this problem to Discourse: https://meta.discourse.org/t/problem-with-details-tag-in-lists/58729/2

**Comment by tmihoc** [comment]
> Hi @tmihoc this is probably a Discourse limitation. I found this post from a user reporting this problem to Discourse: https://meta.discourse.org/t/problem-with-details-tag-in-lists/58729/2

I've been playing with some of the suggestions. 

This:
```
- A
    [details=Expand]
    - a
    [/details]
- B
```
yields this:

![image](https://user-images.githubusercontent.com/38667005/171108782-2062147d-4f02-4adc-b121-3d7641191d2b.png)


This is almost what I want, but not quite---there's a large gap before B on the unexpanded view:

![image](https://user-images.githubusercontent.com/38667005/171108876-a72dad33-7941-4b1d-996c-bdcf18ccb1e6.png)

Any further suggestions?

**Comment by tmihoc** [comment]
> @tmihoc, I think we might be able to fix that gap. Is it happening on our website docs or Discourse?

It's happening on the website. (Possibly also Discourse, but what I care about the most is the website view.) 
 
> Could you use it and point us to a page with it so we can have a look? Thank you!

Well, I'm not using it currently in the docs, because the result doesn't look good. But I can give you a quick live demo in a meeting, if it helps.

**Comment by jkfran** [comment]
Hi @tmihoc we fixed the spacing issue in the website docs. I didn't have any issues with links inside the details on my tests, this is the markdown I used:
```
- A
    [details=Expand]
    - [link](/t/6137)
    [/details]
- B
```
You can start using it now :)

**Comment by tmihoc** [comment]
Insofar as I can see, the problem persists. Your code yields:

![image](https://user-images.githubusercontent.com/38667005/173552837-1bcdb755-b29e-4ba4-9702-cc3b665828db.png)

(Tried on https://discourse.charmhub.io/t/olm-reference/5348 , see commented out text at the top of the doc.)

**Comment by jkfran** [comment]
@tmihoc we fixed the website styling, so I meant on juju.is/docs but now that you mentioned it I applied the same fix on Discourse. Please check again.

**Comment by tmihoc** [comment]
> @tmihoc we fixed the website styling, so I meant on juju.is/docs but now that you mentioned it I applied the same fix on Discourse. Please check again.

Looks good now, thanks!
